### ISSUE TITLE
[Feature]: @append="append"

### ISSUE THREAD

**Issue by nathanchase** [DerYeger/vue2-masonry-wall#13]
### Description

Your version of vue-masonry wall works great in my app, but I was wondering if you would consider including the endless scroll functionality `@append="append"` from [the original](https://github.com/fuxingloh/vue-masonry-wall), where the interaction observer auto-loads a function to append new items to the masonry wall items object?

Basically the same implementation from https://github.com/fuxingloh/vue-masonry-wall/blob/a02d49c78cfda9a7dcaadefe7a30f67ea010f590/src/vue-masonry-wall.vue#L10 - but for your version (that includes support for add/removal of items).

Thanks! 

### Solution

Support `@append="append"` functionality from original vue-masonry-wall.

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by frdrk** [comment]
Would be very interested in this as well.

**Comment by frdrk** [comment]
If this feature is not being considered at the moment any change you can point me in the direction on how to add the functionality temporarily? 

I'm using the Intersection Observer API to add items to the original array but that leads to duplicated key, scrolling issues and flashing content. Not sure if it's how redraw is done perhaps?

**Comment by DerYeger** [comment]
Unfortunately, I won't have time for my OSS projects for the foreseeable future.

Regarding this issue, I can't think of a good solution that supports both adding and removing items without reassigning the entire input array.

As a workaround on your end, I think it should be possible to put an Intersection Observer element below the component. Then, whenever it intersects, fetch a new item and re-assign the prop `items` to `[...oldItems, newItem]`. This approach for adding items should work as seen [in the demo](https://vue2-masonry-wall.yeger.eu).

**Comment by frdrk** [comment]
That is exactly how I am doing it actually. It turns out it was my fault for trying to remap item values after I had merged in new images. Works pretty well now that I've changed that. Thank you!

**Comment by DerYeger** [comment]
Considering that the approach described [here](https://github.com/DerYeger/vue2-masonry-wall/issues/13#issuecomment-1114169991) enables this functionality without massive changes to this library, I'll close the issue.

**Comment by nathanchase** [comment]
> That is exactly how I am doing it actually. It turns out it was my fault for trying to remap item values after I had merged in new images. Works pretty well now that I've changed that. Thank you!

Do you have an example on GitHub showing how this works? I'm unable to get Intersection Observer to not fire immediately on page load and try to load more data, or it fires on page load and then again when the masonry wall items load and render.
