### ISSUE TITLE
[Bug]: Gap flexbox is not supported in Safari 14.0.3

### ISSUE THREAD

**Issue by archieDeveloper** [DerYeger/vue2-masonry-wall#15]
### Description

Not work gap flexbox in Safari 14.0.3

### Reproduction

Open page https://vue2-masonry-wall.yeger.eu/ in Safari 14.0.3

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by archieDeveloper** [comment]
As a solution to the problem, I set :gap="0" and wrote css rules for masonry classes.

```
$grid-gutter-width: 24px;
.masonry {
  &-column {
    margin-right: $grid-gutter-width / 2;
    margin-left: $grid-gutter-width / 2;
    margin-top: -$grid-gutter-width;
  }
  &-item {
    margin-top: $grid-gutter-width;
  }
  &-wall {
    margin-right: -$grid-gutter-width / 2;
    margin-left: -$grid-gutter-width / 2;
  }
}
```

**Comment by DerYeger** [comment]
Thanks for reporting this and posting a workaround.
Due to time constraints, I won't work on this for now and I'm not sure how relevant this will be for future Safari versions.
