### ISSUE TITLE
[Question]: Desktop - 2 columns, Mobile - 1 column

### ISSUE THREAD

**Issue by RokasDie** [DerYeger/vue2-masonry-wall#36]
### Description

Hello,

I wanted to ask, how this package should be used for mobile view. For desktop it works perfectly as I load with these options:
```
 <masonry-wall
      v-if="posts.length > 0"
      :items="posts"
      :ssr-columns="2"
      :column-width="300"
      :gap="16"
    >
```

However, with mobile I have a problem. The first second shows two columns and then it turns into one. I would like that mobile view would load with 1 column, with no transition

Cheers!

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by RokasDie** [comment]
Removing `ssr-columns` solved the issue

**Comment by DerYeger** [comment]
> Removing `ssr-columns` solved the issue

Yes, the server doesn't know the screen size.
Either disabling SSR for this component or using `:ssr-columns="1"` should work.
