### ISSUE TITLE
[Documentation]: Still @append etc?

### ISSUE THREAD

**Issue by JMKelley** [DerYeger/vue2-masonry-wall#37]
### Description

Your module is exactly what I'm looking for.

Just checking is it still @append and similar docs from the original or has it been rewritten?

Thanks in advance.

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Hi, there's no equivalent to @append. You can place an IntersectionObserver below the component and trigger an update to the items property whenever it intersects.

**Comment by DerYeger** [comment]
The component itself has been mostly rewritten, with bug fixes and a focus on static layouts (hence @append has been removed).

**Comment by JMKelley** [comment]
Ah ok - good stuff.

Thanks
