### ISSUE TITLE
Example with NuxtJS v2?

### ISSUE THREAD

**Issue by dosstx** [DerYeger/vue2-masonry-wall#5]
Excellent package! I am using NuxJS2 and in my initial tests, everything seems to be working appropriately with SSR. I have my example here: https://codesandbox.io/s/yeger-masonry-vue2-v03xv?file=/pages/index.vue

However, I am wondering if my attempt is the best way to do it. Just wondering if you had any thoughts on using vue2-masonry-wall with NuxtJS? How would you do it? 

With the release of NuxtJS3 on the horizon, wondering if you would also be able to have an example using that version, as well (when released).

Thanks and keep up the great work.

**Comment by DerYeger** [comment]
Thank you!

I'm using this component myself. Checkout [this](https://github.com/DerYeger/jan-mueller/blob/fab41340e8af3ece4aab615b34d87728a04f67c8/pages/projects/index.vue) Nuxt page. Simply specifying `ssr-columns` is all you need.

I'll update my projects as soon as possible to Nuxt 3. [@yeger/vue-masonry-wall](https://github.com/DerYeger/vue-masonry-wall) should be a drop in replacement without any template changes. You should only have to update the component import to match the Vue 3 method.
